INSERT INTO room (name) VALUES
    ('Chambre'),
    ('Salon'),
    ('Cuisine'),
    ('Entrée'),
    ('Salle de bains')
;

INSERT INTO user (username) VALUES
    ('Aliette'),
    ('Joey'),
    ('Beline')
;

INSERT INTO frequency (name) VALUES
    ('hours'),
    ('days'),
    ('weeks'),
    ('months'),
    ('years')
;

INSERT INTO task (room_id, last_done_by_id, name, duration, frequency_id, difficulty, last_done, next_done)VALUES
    (1, null, 'Passer l\'aspirateur', 1, 2, 1, null, DATE_ADD(now(), INTERVAL 1 DAY)),
    (1, null, 'Nettoyer la table de chevet', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (1, null, 'Faire la poussière', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (1, null, 'Passer la serpillière', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (1, null, 'Changer les draps', 2, 3, 3, null, DATE_ADD(now(), INTERVAL 2 WEEK)),
    (1, null, 'Nettoyer les interrupteurs et les prises', 1, 4, 1, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (1, null, 'Nettoyer sous le lit', 1, 4, 3, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (1, null, 'Tri de la garde-robe', 6, 4, 2, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (1, null, 'Laver les oreillers', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (1, null, 'Laver les couvertures', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (1, null, 'Laver les vitres', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (1, null, 'Laver les radiateurs', 6, 4, 2, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (1, null, 'Laver la porte', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (1, null, 'Nettoyer le plafond et les spots', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (1, null, 'Nettoyer les plinthes', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (1, null, 'Laver les rideaux', 1, 5, 3, null, DATE_ADD(now(), INTERVAL 1 YEAR)),
    (2, null, 'Passer l\'aspirateur', 1, 2, 1, null, DATE_ADD(now(), INTERVAL 1 DAY)),
    (2, null, 'Passer la serpillière', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (2, null, 'Nettoyer les écrans', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (2, null, 'Faire la poussière', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (2, null, 'Ré-organiser les étagères', 3, 4, 3, null, DATE_ADD(now(), INTERVAL 3 WEEK)),
    (2, null, 'Nettoyer les interrupteurs et les prises', 1, 4, 1, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (2, null, 'Laver les vitres', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (2, null, 'Laver les radiateurs', 6, 4, 2, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (2, null, 'Nettoyer le plafond et les spots', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (2, null, 'Nettoyer les plinthes', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (2, null, 'Laver les rideaux', 1, 5, 3, null, DATE_ADD(now(), INTERVAL 1 YEAR)),
    (3, null, 'Faire la vaisselle', 12, 1, 2, null, DATE_ADD(now(), INTERVAL 12 HOUR)),
    (3, null, 'Sortir le compost', 1, 2, 1, null, DATE_ADD(now(), INTERVAL 1 DAY)),
    (3, null, 'Nettoyer le plan de travail', 1, 2, 2, null, DATE_ADD(now(), INTERVAL 1 DAY)),
    (3, null, 'Passer l\'aspirateur', 1, 2, 1, null, DATE_ADD(now(), INTERVAL 1 DAY)),
    (3, null, 'Nettoyer l\'évier et les canalisations', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (3, null, 'Faire la poussière', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (3, null, 'Passer la serpillière', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (3, null, 'Sortir les poubelles', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (3, null, 'Nettoyer le four', 1, 4, 3, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (3, null, 'Nettoyer le micro-ondes', 1, 4, 3, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (3, null, 'Détartrer la bouilloire', 1, 4, 2, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (3, null, 'Nettoyer les poubelles', 1, 4, 3, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (3, null, 'Nettoyer le grille-pain', 1, 4, 2, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (3, null, 'Nettoyer les interrupteurs et les prises', 1, 4, 1, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (3, null, 'Détartrer la cafetière', 2, 4, 2, null, DATE_ADD(now(), INTERVAL 2 MONTH)),
    (3, null, 'Nettoyer le frigo', 1, 4, 3, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (3, null, 'Nettoyer le freezer', 3, 4, 3, null, DATE_ADD(now(), INTERVAL 3 MONTH)),
    (3, null, 'Nettoyer le lave-vaisselle', 3, 4, 3, null, DATE_ADD(now(), INTERVAL 3 MONTH)),
    (4, null, 'Passer l\'aspirateur', 1, 2, 1, null, DATE_ADD(now(), INTERVAL 1 DAY)),
    (4, null, 'Faire la poussière', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (4, null, 'Passer la serpillière', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (4, null, 'Nettoyer les chaussures', 1, 4, 2, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (4, null, 'Nettoyer les miroirs', 1, 4, 2, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (4, null, 'Nettoyer les interrupteurs et les prises', 1, 4, 1, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (4, null, 'Nettoyer le placard', 1, 4, 3, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (4, null, 'Nettoyer les manteaux', 4, 4, 3, null, DATE_ADD(now(), INTERVAL 4 MONTH)),
    (4, null, 'Tri des manteaux', 6, 4, 2, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (4, null, 'Nettoyer les plinthes', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (4, null, 'Laver la porte', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (4, null, 'Nettoyer le plafond et les spots', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (5, null, 'Passer l\'aspirateur', 1, 2, 1, null, DATE_ADD(now(), INTERVAL 1 DAY)),
    (5, null, 'Nettoyer la douche', 1, 3, 3, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Nettoyer le lavabo', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Nettoyer le miroir', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Nettoyer les toilettes', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Faire la poussière', 1, 3, 1, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Passer la serpillière', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Changer le tapis de bain', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Changer les serviettes', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Nettoyer la brosse', 1, 3, 2, null, DATE_ADD(now(), INTERVAL 1 WEEK)),
    (5, null, 'Nettoyer le placard', 1, 4, 3, null, DATE_ADD(now(), INTERVAL 1 MONTH)),
    (5, null, 'Nettoyer les plinthes', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (5, null, 'Laver la porte', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH)),
    (5, null, 'Nettoyer le plafond et les spots', 6, 4, 3, null, DATE_ADD(now(), INTERVAL 6 MONTH))
;
